apiVersion: v1
kind: Service
metadata:
  name: kokoro-wake-detector-service
  labels:
    app: kokoro-wake-detector
spec:
  selector:
    app: kokoro-wake-detector
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP